# Generated by Django 4.1.3 on 2022-11-11 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_user_options_product_delete_at_product_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='carts',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
