# Generated by Django 4.1.3 on 2022-11-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_tags_alter_tag_name_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
