# Generated by Django 4.1.3 on 2022-11-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_content_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='delete_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
